-- Persistent semantic classification review queue.
create table if not exists public.classification_review_queue (
  id bigint generated by default as identity primary key,
  brand_id text not null,
  source text not null,
  title text not null,
  source_path text,
  knowledge_scope text not null default 'unknown',
  owner text not null default 'unknown',
  entity_name text,
  document_type text not null default 'general',
  classification_confidence double precision not null default 0.05,
  classification_reason text not null default '',
  status text not null default 'pending',
  proposed_metadata jsonb not null default '{}'::jsonb,
  reviewer text,
  review_notes text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (brand_id, source)
);

create index if not exists classification_review_queue_status_idx
  on public.classification_review_queue (brand_id, status, created_at);

create index if not exists classification_review_queue_scope_idx
  on public.classification_review_queue (knowledge_scope, status);

insert into public.classification_review_queue (
  brand_id, source, title, source_path, knowledge_scope, owner, entity_name,
  document_type, classification_confidence, classification_reason, proposed_metadata
)
select
  bc.brand_id,
  bc.source,
  max(bc.title),
  max(bc.source_path),
  max(bc.knowledge_scope),
  max(bc.owner),
  max(bc.entity_name),
  max(bc.document_type),
  min(bc.classification_confidence),
  'Existing indexed content has no reliable semantic classification yet.',
  jsonb_build_object(
    'knowledge_scope', max(bc.knowledge_scope),
    'owner', max(bc.owner),
    'entity_name', max(bc.entity_name),
    'document_type', max(bc.document_type),
    'classification_confidence', min(bc.classification_confidence)
  )
from public.brand_chunks bc
where bc.knowledge_scope = 'unknown'
group by bc.brand_id, bc.source
on conflict (brand_id, source) do nothing;
